import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";
import { useState } from "react";

const CreatePostWizard = () => {
  const { data: session, status } = useSession();
  const [input, setInput] = useState("");
  const ctx = api.useContext();

  const { mutate } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate();
    },
    onError: (err) => {
      console.error(err);
    }
  });

  if (status === "authenticated") {
    return (
      <div className="p-8 flex gap-3 justify-center">
        <img src={session.user?.image!} className="rounded-full w-8 h-8" />
        <input 
          value={input}
          onChange={(e) => setInput(e.target.value)}
          type="text" 
          maxLength={100}
          placeholder="Enter a task!" 
          className="grow bg-transparent text-threads-bg-dark border rounded-full border-slate-100 p-2" 
        />
        <button onClick={() => mutate({content: input}) }className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">
          Enter
        </button>
      </div>
    );
  }
  return null;
  
};

function AuthWizard() {
  const { data: sessionData } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}

export default function Home() {
  const { data: session } = useSession();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div> ...Loading </div>

  if(!data) return <div>fook</div>

  return (
    <>
      <Head>
        <title>T3eads</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full md:max-w-2xl border-x">
          <div>
            {data?.map(({post,author}) => (<div key={post.id}>{post.content}<img src={author?.image!}/></div>))}
          </div>
          <div>
            <CreatePostWizard />
            <AuthWizard/>
          </div>
          <div className="flex items-center justify-between p-4 text-xl">
            <a href="https://github.com/t3dotgg/chirp">
              <div className="flex items-center justify-center gap-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="white"
                >
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                </svg>
                <div>Github</div>
              </div>
            </a>
            <span>
              <a href="https://patreon.com/t3dotgg">🐦 Chirp Blue</a>
            </span>
          </div>
        </div>

      </main>
    </>
  );
}


